path_specific: "mnist_wqvae/"
  
dataset:
  name: 'MNIST'
  shape: (1, 32, 32)
  dim_x: 1024 # 1 * 28 * 28

model:
  name: "VQWAE"

network:
  name: "resnet"
  num_rb: 2

train:
  lr: 0.001
  bs: 32
  epoch_max: 100
  
quantization:
  name: 'VQVAE'
  global_optimization: False
  fixed_weight: False
  size_dict: 512
  dim_dict: 64
  beta: 0.25
  init_weight: 'uniform' # gaussian, peaked, uniform, gaussian200
  kl_regularization: 0.0

generation:
  lr: 0.0002
  n_critic: 5
  temperature: 1.0